services:
  php:
    build:
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      - ./app:/var/www/html
    networks:
      wot-collision-network:
        ipv4_address: 172.83.17.11

  nginx:
    image: nginx:latest
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      wot-collision-network:
        ipv4_address: 172.83.17.12

  mysql:
    image: mysql:latest
    volumes:
      - ./docker/mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    networks:
      wot-collision-network:
        ipv4_address: 172.83.17.13

networks:
  wot-collision-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.83.17.0/24
